<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-Transitional.dtd">
<html><head><title></title></head>
<body>
<?php $postID=4202011;?>
<!-- Original Date  -->

<div id="title">Babel</div>
<div id="text">
<i> - April 20, 2011</i><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I recently heard a criticism of American culture, that our thoughts recklessly center around the individual whereas other cultures put more stock in the value and the power of their community. This argument asserts that the quest for personal power and accomplishment that so governs our thinking leads to success for very few. This, the argument concludes, allows for a minority of people to live in a manner where they gain a majority of the wealth and power, leaving all others gasping in their wake. <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To a point, I have to agree. While "rugged individualism" is a vital part of the American ideal, it certainly should not be taken to an extreme. However, I cannot claim that working as a community is always a better option. While  individualism becomes harmful when the individual is put above all else, community comes apart when one or more members insist that each member must lose all autonomy if he or she is to claim the benefits of the community. Harmful things come when each member of a group <i>must</i> believe and act upon certain ideals or they are not truly part of the group. <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This problem is rooted in the ancient Tower of Babel (Genisis 11:1-8). When all people had the same language, the power of community never was more evident. God himself declared that "nothing is impossible" for them, even though they were united in a wicked purpose. While some might see God's response to this situation as punishment, it really was his mercy that lead him to confuse their speech and unravel the community they had created. He disarmed the threat  that a fallen community posed to its members.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That is not to say that the goal of bringing together like-minded people with a high purpose is not good in itself. Such a community, if it is Christ-centered, is the essence of Christianity. But, like all other good things God meant for good, we must invite him to redeem and restore our understanding of community or it will become a weapon and an enemy in one foul package. <b>AP</b>
</div>
</body></html>
