--change the primary key
--new column for new primary key
--reorder database so that order of primary key is order of posts
--create and populate post_text
DROP TABLE IF EXISTS `post`;
CREATE TABLE IF NOT EXISTS `post` (
  `postID` char(10) NOT NULL,
  `title` varchar(45) DEFAULT NULL,
  `date` varchar(45) DEFAULT NULL,
  `current_post` binary(1) NOT NULL DEFAULT '0',
  `sysdate` datetime NOT NULL,
  `post_rowid` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`post_rowid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1 ;

INSERT INTO `post` (`postID`, `title`, `date`, `current_post`, `sysdate`) VALUES
('Jan292011','Mercy','January 29, 2011',0,'2011-01-29 00:00:00'),
('Feb062011','Distance','February 6, 2011',0,'2011-02-06 00:00:00'),
('Apr032011','Soldiers','April 3, 2011',0,'2011-04-03 00:00:00'),
('Oct52012','Ripples','October 5, 2012',0,'2012-10-05 00:00:00'),
('Oct262012','Dust','October 26, 2012',0,'2012-10-26 00:00:00'),
('Oct302012','Sandy','October 30, 2012',0,'2012-10-30 00:00:00'),
('Nov202012','Election','November 20, 2012',0,'2012-11-20 00:00:00'),
('Dec282012','Mirror','December 28, 2012',0,'2012-12-28 00:00:00'),
('Feb212013','Rescued','February 21, 2013',0,'2013-02-21 00:00:00'),
('May222013','Cold','May 22, 2013',0,'2013-05-22 17:40:00'),
('Jul312013','Coffee','July 31, 2013',0,'2013-07-31 15:16:10'),
('Sep92013','Spinning','September 9, 2013',0,'2013-09-09 09:49:10'),
('Sep242013','Crosswalk','September 24, 2013',0,'2013-09-24 17:57:20'),
('Jan162014','Dream','January 16, 2014',0,'2014-01-16 13:33:20'),
('Jan302014','Worst','January 30, 2014',0,'2014-01-31 00:00:00'),
('Feb42014','Unsaid','February 4, 2014',0,'2014-02-04 17:13:30'),
('Feb52014','Learning','February 5, 2014',0,'2014-02-05 14:46:10'),
('Mar122014','Weary','March 12, 2014',0,'2014-03-12 13:47:30'),
('Apr12014','Trickster','April 1, 2014',0,'2014-04-01 11:37:20'),
('Apr22014','Incident','April 2, 2014',1,'2014-04-02 00:00:00');

DROP TABLE IF EXISTS `post_text`;
CREATE TABLE IF NOT EXISTS `post_text` (
  `post_text_rowid` int(11) NOT NULL AUTO_INCREMENT,
  `post_rowid` int(11) NOT NULL,
  `post_content` text COLLATE latin1_general_ci,
  PRIMARY KEY (`post_text_rowid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci AUTO_INCREMENT=1 ;

INSERT INTO `post_text` (`post_rowid`, `post_content`) VALUES
(1, '<span class=''title''><b>Mercy</b></span><span class=''date''> - February 6, 2011</span></p><span class=''postbodytext''><p>Oh, I know</p><p>We''re not aware of it</p><p>Because we are upright enough,</p><p>Skilled enough,</p><p>Okay enough,</p><p>We''ve tried and more than tried.</p><p>We have received mercy by this,</p><p>This permission to fill a life up full.</p><p>Well, as full as one can make it.</p><p>And God is kind, oh He is kind!</p><p>To let us hold up the world this way,</p><p>To breathe in our days,</p><p>To have oceans in our eyes,</p><br/><p>And to step, though we may</p><p>Fall into the life we are scraping out of the earth,</p><p>For all our scraping was digging our graves.</p></span>'),
(2, '<span class=''title''><b>Distance</b></span><span class=''date''> - February 6, 2011</span><br/><span class=''postbodytext''><p>You drove a wedge between</p><p>You and reality,</p><p>And none of what''s been planted</p><p>Will be seen.</p><p><p>To plow against the wind</p><p>And with the rocks and trees,</p><p>Now you lift the soil</p><p>To throw it as you please.</p><p></p><p>No matter what you believe</p><p>Your distance is extreme</p></span>'),
(3, '<span class=''title''><b>Soldiers</b></span><span class=''date''> - April 3, 2011</span><br/><span class=''postbodytext''><p>My heart is also for those who wait</p><p>With a star in a window and the fear,</p><p>Who have no war to draw their minds</p><p>From thoughts of the one who is not there.</p><p>One day, when each one has come back</p><p>When all the praises are being sung,</p><p>Thank those who fought these wars at home</p><p>And those who fought them so very young.</p></span>'),
(4, '<span class=''title''><b>Ripples</b></span><span class=''date''> - October 5, 2012</span><span class=''postbodytext''><p>Life, </p><p>Both with its repetitions and its irregularities </p><p>Together making expectation impossible and unwise,</p><p>Then, startling me awake from its lulling rhythms</p><p>By some mischievous wave.</p><p>If I focus on the rocking of the boat </p><p>Or the waves against the shore</p><p>I will go crazy expecting that some great difference will appear.</p><p>Yet, when I look away</p><p>When life is going by nearly unnoticed </p><p>A leaf falls into the pond or a branch</p><p>It crashes with drama and intensity</p><p>Casting ripples that do not easily subside</p><p>But become part of the motion</p><p>That will be my every day</p><p>Drawing from out of the center some energy</p><p>That I can neither harness nor re-create.</p></span>'),
(5, '<span class=''title''>Dust</span><span class=''date''> - October 26, 2012</span><br/><span class=''postbodytext''><p>I found a thought,</p><p>A wonderful thought.</p><p>So I cornered it, but it ran through me,</p><p>Into the trees.</p><p>I chased it dutifully, though my skin was torn,</p><p>Though all the brush was trampled upon</p><p>Until down it went into a hole in the earth.</p><p>I dug at it madly,</p><p>And found it had turned to dust,</p><p>Mixed into the soil from which it had come.</p></span>'),
(6, '<span class=''title''>Sandy</span><span class=''date''> - October 30, 2012</span><br/><span class=''postbodytext''><p>Joy at the black</p><p>And deep clouds</p><p>Bearing down,</p><p>Crushing the light--</p><p>A bitter storm</p><p>May seem meager sustenance for a song.</p><p>Nor do I hope against hope that I see light</p><p>At the shady edge of the sky,</p><p>For I rarely see any.</p><p>There may be light on the horizon,</p><p>And there may not be,</p><p>But there is light beyond the horizon.</p><p>That is a certainty.</p><p>Light and a world </p><p>That I see, clear as day,</p><p>With my heart.</p></span>'),
(7, '<span class=''title''>Election</span><span class=''date''> - November 20, 2012</span><br/><span class=''postbodytext''><p>Baby birds,</p><p>Their mouths open before their eyes do.</p><p>Their wobbling heads follow the mother''s beak,</p><p>Stumbling over each other and themselves</p><p>For worms.</p></span><br/><br/><br/><br/><br/><br/>'),
(8, '<span class=''title''>Mirror</span><span class=''date''> - December 28, 2012</span><br/><span class=''postbodytext''><p>I would have liked to set the whole thing on his desk</p><p>To see it there taking up space,</p><p>Even for a moment, would have been enough.</p><p>I have no wish to leap in front of people</p><p>But only a need for evidence against the notion</p><p>That I bear no weight upon the earth.</p><p>When we got within 100 feet of the "salty"--</p><p>It was a city on Superior''s waves--</p><p>We did not cower as it stood over us.</p><p>The sailboats danced around it</p><p>Like fairies at the ogre''s feet.</p><p>Then, I wanted to write that I saw these things</p><p>I needed to enter it into the record.</p><p>So that I could say without a doubt</p><p>I was here.</p></span>'),
(9, '<span class=''title''>Rescued</span><span class=''date''> - February 21, 2013</span><br/><span class=''postbodytext''><p>I pride myself on being a quiet person.</p><p>I don''t carry noise around with me everywhere,</p><p>I don''t whistle or keep the radio on for no reason.</p><p>But when I am surrounded by complaints</p><p>And I feel as though I am</p><p>Being dragged by the plow,</p><p>I find myself in a panic, fearing silence</p><p>Like the lost hiker who fled</p><p>At the sound of the rescue party.</p><p>It just doesn''t demand anything,</p><p>And demands are the language of this world,</p><p>So silence comes, speaking words</p><p>Of which, I''ve forgotten the meaning</p><p>But the rhythms haunt me.</p><p>And I am secreted away and rescued once again.</p></span>'),
(10, '<span class=''title''>Cold</span><span class=''date''> - May 22, 2013</span><br/><span class=''postbodytext''><p>I suspect that, as most people age,</p><p>They leave their hearts behind.</p><p>When the cares of life </p><p>Somehow get exaulted to gods,</p><p>When wealth seems possible,</p><p>Or at least the wealth of not being destitute,</p><p>Makes its way in to the folds of the brain.</p><p>And the Judas in the mind says the heart should go</p><p>And gets paid for it.</p><p>I suspect this will happen to me</p><p>If I am not careful. </p></span>'),
(11, '<span class=''title''>Coffee</span><span class=''date''> - July 31, 2013</span><br/><span class=''postbodytext''><p>I don''t know why,</p><p>But I like coffee at night.</p><p>Perhaps that is because it is when I most need it.</p><p>Unlike many, the morning, to me, is not a pit to dig out of</p><p>But more like standing on a grave</p><p>With yesterday safely beneath my feet.</p><p>Nor am I afraid that it will keep me awake,</p><p>For I am always miles from my bed.</p><p>But as the sun races to the other side,</p><p>I am most likely to feel despair</p><p>Slipping down my throat--</p><p>A hot, bitter assault, strong, merciless</p><p>And black as the night that now surrounds me.</p><p>I suppose, when I say it this way,</p><p>It does not seem so strange. </p></span>'),
(12, '<span class=''title''>Spinning</span><span class=''date''> - September 9, 2013</span><br/><span class=''postbodytext''><p>What should I say then? </p><p>Are we all lost? </p><p>Is this the mystery </p><p>Or the other&#150;oh the other. </p><p>Why did we have to bring all that </p><p>To sort of boil now? </p><p>I know. </p><p>I know the world spins on these things. </p><p>Different things, </p><p>Lost things. </p><p>I only want to be sure </p><p>It is really turning </p><p>And not shearing off.</p></span>'),
(13, '<span class=''title''>Crosswalk</span><span class=''date''> - September 24, 2013</span><br/><span class=''postbodytext''><p>Naive streets stretch out</p><p>Like worn cords,</p><p>Woven in lines no one can comprehend.</p><p>And we are stuck in the crosshatches, </p><p>Struggling fish</p><p>An indifferent net,</p><p>The demands of order hauling us up.</p><p>Yet there is a trick in it,</p><p>A divine and devious turn.</p><p>It''s that orange hand on the street light.</p><p>So many disobey it thinking they are defeating it,</p><p>Or likely feeling to busy for orange hands</p><p>When in fact they are playing a very tedious game.</p><p>Playing at "making things happen".</p><p>I don''t keep walking, writhing,</p><p>Though, everything tells me I should.</p><p>I''ll wait for it to turn.</p></span>'),
(14, '<span class=''title''>Dream</span><span class=''date''> - January 16, 2014</span><br/><span class=''postbodytext''><p>It came crushing down.</p><p>The ceiling of my bedroom, dust and plaster</p><p>I was lifted,</p><p>And the rain clouds folded sky-born oceans over me.</p><p>The clouds enveloped me,</p><p>And I could no longer hear the shouts,</p><p>And no one called me “Condemed!”</p><p>It was just the wind,</p><p>The tops of the trees laughing, but not at me.</p><p>And this would be good enough for the time. </p><br/><p>I do not want you to fill my broken heart</p><p>With pasty white songs of vague happiness.</p><p>I want you to heal it.</p><p>Can you do that?</p></span>'),
(15, '<span class=''title''>Worst</span><span class=''date''> - January 30, 2014</span><br/><span class=''postbodytext''><p>It came like a storm,</p><p>Slowly, from a long way off.</p><p>Me? I was watching.<br/><br/><br/><br/><br/><br/><br/><br/></p></span>'),
(16, '<span class=''title''>Unsaid</span><span class=''date''> - February 4, 2014</span><br/><span class=''postbodytext''><p>It was what you didn''t say.</p><p>It went</p><p>Unsaid when the world was mine</p><p>Unsaid when the world was gone</p><p>Unsaid in a thousand tears</p><p>Unsaid in lonely song</p><p>Down a road</p><p>The gathering dusk</p><p>Nowhere to turn.</p></span>'),
(17, '<span class=''title''>Learning</span><span class=''date''> - February 5, 2014</span><br/><span class=''postbodytext''><p>I believe it.</p><p>Learning: your brain making new connections.</p><p>I can feel it happening</p><p>Like workers in two ends of a tunnel</p><p>Finally meeting.</p><p>However it happens</p><p>Energy, impossible to quantify,</p><p>Going on a journey it has never taken before.</p><p>Alarmingly beautiful,</p><p>Suprisingly familiar.</p></span>'),
(18, '<span class=''title''>Weary</span><span class=''date''> - March 12, 2014</span><br/><span class=''postbodytext''><p>It snowed again last night.</p><p>Overpowering the warmth</p><p>We''re sick of shovels.</p><br/><br/><br/><br/><br/><br/><br/><br/><br/></span>'),
(19, '<span class=''title''><b>Trickster</b></span><span class=''date''> - April 1, 2014</span><br/><span class=''postbodytext''><p>Nature, first trickster,</p><p>Told us "Spring" weeks ago, now.</p><p>It''s been snowing since.</p></span><br/><br/><br/><br/><br/><br/><br/><br/><br/>'),
(20, '<span class=''title''>Incident</span><span class=''date''> - April 2, 2014</span><br/><span class=''postbodytext''><p>While I paid the cashier,</p><p>A man came behind me with myriad packages</p><p>Of bologna</p><p>And an incomprehensible assortment</p><p>Of coupons.</p><p>He looked at the cashier</p><p>And in a grim voice,</p><p>"Let me explain what happened"</p><p>"--after he''s done", jesturing vaguely to me.</p><p>I could not fathom this man''s day--</p><p>Suddenly, unexpectedly</p><p>His life collided with a lunch meat issue</p><p>He had to wait for me to leave</p><p>Before he could find the words.</p></span>');