<?php 
/*DEV*/
$mysql_host="localhost";
$mysql_user="root";
$mysql_password="R0mans12";
$mysql_database="tersedev";

/*PROD*/
//$mysql_host = "127.3.81.2";
//$mysql_database = "terse_db";
//$mysql_user = "adminQ5Iknaz";
//$mysql_password = "8nypqRzJA1fw";

//$mainURL  = "http://aaronpriest-terse.rhcloud.com"; //This is used in publish and ./feed/index.php
$mainURL  = "http://localhost:8080/xampp/terse"; 

?>
